In [3]:
import numpy as np

In [4]:
import matplotlib.pyplot as plt

In [5]:
import pandas as pd

In [6]:
dataset = pd.read_csv("trafficstop.csv")

In [7]:
dataset

Month  RsnStop  OffRace  OffMale  OffYrsSrv  DrvRace  DrvHisp  DrvMale  \
0          8        8      3.0        0         22        2        2        1   
1          1        8      5.0        1         18        2        2        1   
2          1        8      5.0        1         18        2        2        0   
3         11        7      3.0        0         23        5        1        1   
4         12        7      3.0        0         23        5        2        1   
5          4       10      5.0        1         22        2        2        1   
6          1        5      5.0        1         14        2        2        1   
7          3        8      5.0        1          7        2        2        1   
8          8        8      5.0        1          9        2        2        1   
9          8        5      5.0        1         17        5        2        1   
10         3        4      5.0        0          3        5        2        0   
11        11       10      3.0        1          7        2        2        1   
12        11       10      5.0        1          4        2        2        0   
13         2        7      5.0        1          9        2        2        0   
14         1        7      2.0        1         10        2        2        0   
15         3       10      5.0        1         17        5        2        0   
16         4        7      5.0        1         22        4        2        0   
17         4        7      5.0        1         22        2        2        0   
18         4        7      5.0        1         22        4        1        1   
19         4        9      5.0        1          7        2        2        1   
20         4        9      5.0        1          7        2        2        1   
21         4       10      5.0        1          7        2        2        1   
22         4        4      5.0        1          7        2        2        1   
23         4       10      5.0        1          3        2        2        0   
24         1       10      2.0        1         19        5        2        0   
25         1        7      5.0        1          6        5        2        0   
26         1        5      5.0        1          3        2        2        0   
27         1       10      5.0        1          1        2        2        1   
28         1       10      5.0        1         23        2        2        0   
29         1        4      3.0        1          2        5        1        1   
...      ...      ...      ...      ...        ...      ...      ...      ...   
79854     12        7      3.0        1         15        2        2        1   
79855     12       10      5.0        1         23        5        2        0   
79856     12        7      3.0        1         15        5        1        0   
79857     12        7      2.0        1         20        5        1        1   
79858     12        7      3.0        1         15        2        2        0   
79859     12       10      3.0        1          7        2        2        1   
79860     12        8      5.0        1         16        5        2        1   
79861      2        7      5.0        1          7        2        2        1   
79862      6        9      5.0        1         11        5        2        0   
79863      5        3      5.0        1          9        5        2        1   
79864      9        9      5.0        1         11        2        2        1   
79865      2       10      3.0        1         23        5        2        1   
79866      6        7      5.0        1         22        2        2        1   
79867      2        7      5.0        1         17        2        2        1   
79868      7        7      3.0        1         21        2        2        0   
79869      8        5      3.0        1         25        5        2        1   
79870      3       10      5.0        1          3        5        1        1   
79871      9        7      5.0        

In [8]:
X = dataset.iloc[:,:-1].values

In [9]:
Y = dataset.iloc[:,10].values

In [10]:
X

array([[ 8.,  8.,  3., ...,  1., 40.,  0.],
       [ 1.,  8.,  5., ...,  1., 26.,  1.],
       [ 1.,  8.,  5., ...,  0., 25.,  0.],
       ...,
       [11.,  7.,  5., ...,  1., 72.,  0.],
       [12., 10.,  5., ...,  1., 26.,  0.],
       [11.,  9.,  3., ...,  1., 46.,  0.]])

In [11]:
Y

array([2, 4, 2, ..., 4, 2, 2], dtype=int64)

In [14]:
from sklearn.model_selection import train_test_split

In [15]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 1)

In [16]:
X_train

array([[11.,  7.,  5., ...,  0., 54.,  0.],
       [ 4.,  3.,  5., ...,  1., 34.,  0.],
       [ 9.,  5.,  5., ...,  1., 46.,  0.],
       ...,
       [ 7.,  9.,  5., ...,  1., 55.,  0.],
       [ 1.,  7.,  5., ...,  1., 27.,  0.],
       [12., 10.,  3., ...,  1., 35.,  0.]])